# Generated by Django 4.1.5 on 2023-01-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('course_year', models.CharField(max_length=150)),
                ('instagram_url', models.CharField(max_length=500)),
                ('twitter_url', models.CharField(max_length=500)),
                ('facebook_url', models.CharField(max_length=500)),
                ('confirmation', models.CharField(max_length=10)),
            ],
        ),
    ]
