# Generated by Django 3.2.8 on 2023-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirmation',
        ),
        migrations.AlterField(
            model_name='signup',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
