# Generated by Django 3.2.8 on 2023-01-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('apply_form', '0002_auto_20230129_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotInBuiltUser',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('signup_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='apply_form.signup', verbose_name='user')),
            ],
            bases=('authtoken.token',),
        ),
    ]
